version: '3'

services:
  web:
    build: ./Web/

    command: python web_server_app.py

    ports:
      - 5000:5000

    networks:
      - internet

  dungeon_master:
    build: ./DungeonMaster/

    command: python dungeon_master_app.py

    ports:
      - 88:88

    networks:
      local_network:
        ipv4_address: 172.25.0.11

  room_server:
    build: ./RoomServer/

    command: node dist/server.js

    ports:
      - 4000:4000

    depends_on:
      - dungeon_master

    networks:
      - local_network
      - internet

networks:
  local_network:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.25.0.0/16
  internet:
    driver: bridge